receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Add this line to listen on 4317
      http:
        endpoint: "0.0.0.0:4318"

connectors:
  spanmetrics:
    dimensions:
      - name: worker_id  # Captures worker_id as a Prometheus label
    aggregation_temporality: cumulative

exporters:
  otlp:
    endpoint: "jaeger:4317"  # Ensure it sends traces to Jaeger
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]  # Ensure traces are batched before exporting
      exporters: [otlp, spanmetrics]  # Add spanmetrics as an exporter
    metrics:
      receivers: [spanmetrics]  # Use spanmetrics to generate trace-derived metrics
      processors: [batch]  # Batch metrics before sending to Prometheus
      exporters: [prometheus]  # Export metrics to Prometheus
