global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
